### ISSUE TITLE
front end of day close

### ISSUE THREAD

**Issue by aishatasaduq** [CoalAI/pos-app#273]
Design front end of day close tab in analysis according to mock up.

**Comment by aishatasaduq** [comment]
![image](https://user-images.githubusercontent.com/95906330/168273190-65958d16-ed24-4d1f-bb75-77f585c054ce.png)

**Comment by khunshan-coaldev** [comment]
![image](https://user-images.githubusercontent.com/105208971/168423208-b7567c55-7644-4867-8655-203444e01150.png)

**Comment by khunshan-coaldev** [comment]
![image](https://user-images.githubusercontent.com/105208971/168423399-7144d2e4-7c8d-431f-8ccd-bf657c57767c.png)

**Comment by aishatasaduq** [comment]
PR created with new issue

**Comment by aishatasaduq** [comment]
close #273
